pytorch-ignite/code-generator

src/App.vue
src/components/NavBar.vue
src/components/PaneLeft.vue
src/components/PaneSplit.vue

Fix #104 
Part of #103 
Add a sidebar coming from left to right for left pane on mobile. There is a hamburger button in the bottom right of the window.
Since the navigation and left pane are in each different components, it is difficult to put menu on navigation bar.
Instead I put the menu in the bottom right place of the window. That place could be helpful for full screen smartphones and one-handed users.
The place is inspired by https://reactjs.org/docs/ when viewing on mobile.
---

feat: add sidebar for left pane for mobile

---

src/components/Message.vue
src/components/NavBar.vue
src/store.js

- Add comment about another watch usage
- Set timer for message box since it's annoying if it doesn't disappear after sometime
---

chore: comment another watch usage, timeout message box

---

src/templates/template-vision-segmentation/main.py

Forgot to call `.step()` or attach to trainer
---

fix(template-segmentation): call .step() / attach to engine

---

src/store.js
src/templates/templates.json

Reset `store.code` to empty object after changing templates
---

fix: empty `store.code` after changing templates

---

src/components/FormInput.vue
src/components/TabLoggers.vue
src/store.js

- Have default value for `output_dir` and `log_every_iters` in store
- save the default value when mounting the component
---

fix: default value in store, save on mount

---

scripts/requirements.txt
scripts/run_tests.sh
src/templates/template-common/config.yaml
src/templates/template-text-classification/README.md
src/templates/template-text-classification/config.yaml
src/templates/template-vision-classification/README.md
src/templates/template-vision-classification/config.yaml
src/templates/template-vision-dcgan/README.md
src/templates/template-vision-dcgan/config.yaml
src/templates/template-vision-segmentation/README.md
src/templates/template-vision-segmentation/config.yaml

- Make epochs batch size to larger ones
- Update READMEs (in the coming commits)
ref #103 
---

fix: bump epochs batch size to larger ones, update READMEs

---

package.json
pnpm-lock.yaml
src/components/NavBar.vue
src/components/NavColab.vue

Fix # 
This PR adds "Open in Colab" button button, code adjusted accordingly:
- `README` -> first markdown cell
- `requirements.txt` -> `!pip install <package> <package>`
- `config.yaml` -> `%%writefile config.yaml` (to export config to colab filesystem)
- `main.py` -> at the end (since on Colab `__name__ == "__main__"`)
---

feat: add open in colab

---

functions/colab.js
netlify.toml
package.json
pnpm-lock.yaml
src/components/NavColab.vue
src/components/PaneLeft.vue

fix colab not opening
ref #103 
---

fix: open in colab

---

README.md
app/streamlit_app.py

Add v0.2.0 info and url in old app
ref: #103 
Should be merged after v0.2.0 release
---

Add v0.2.0 info and url in old app

---

.github/workflows/ci.yml
package.json
scripts/run_tests.sh
src/templates/template-vision-segmentation/models.py

Split Ci workflow into several jobs: all, simple, launch, spawn
Fix # 
---

ci: split workflow into several jobs, exclude launch for vision tasks

---

src/components/CodeBlock.vue

Signed-off-by: afzal442 <afzal442@gmail.com>
Fix #164 
---

Shown `txt` file extension

---

src/main.js
src/views/PageNotFound.vue

Signed-off-by: afzal442 <afzal442@gmail.com>
Fix #170 
---

feat: add 404 not found page

---

src/views/PageNotFound.vue

Now navbar will not cover the h1 tag.
fix #180

fix(404): navbar not cover 404 content anymore

---

src/components/TabTraining.vue
src/metadata/metadata.json
src/templates/template-common/README.md
src/templates/template-text-classification/README.md
src/templates/template-vision-classification/README.md
src/templates/template-vision-dcgan/README.md
src/templates/template-vision-segmentation/README.md

Fix #201 
Let me know if I something needs to be changed.

Added Gloo as a backend option

---

src/components/TabTraining.vue
src/metadata/metadata.json

Follow-up PR to #203, adds default backend value.
Otherwise we see an incomplete command:
```sh
python -m torch.distributed.launch \
--nproc_per_node 2 \
--use_env main.py \
--backend 
```
cc @sayantan1410

Added default backend value

---

__tests__/text-classification.spec.js
__tests__/vision-classification.spec.js
__tests__/vision-dcgan.spec.js
__tests__/vision-segmentation.spec.js
package.json
pnpm-lock.yaml
src/components/TabTraining.vue
src/metadata/metadata.json
src/store.js
src/templates/template-common/README.md
src/templates/template-text-classification/README.md
src/templates/template-vision-classification/README.md
src/templates/template-vision-dcgan/README.md
src/templates/template-vision-segmentation/README.md

Added code structure to README and fixed remaining torch.dist.launch with `torchrun`

Added code structure to README and fixed remaining torch.dist.launch

---

.github/workflows/ci.yml
CONTRIBUTING.md
src/templates/template-vision-segmentation/data.py
src/templates/template-vision-segmentation/requirements.txt

Fix # 
- Fixed pnpm version to 7 so that ci is not breaking.
- Cannot perform a frozen installation because the lockfile needs updates
- Refer [pnpm issue #40](https://github.com/pnpm/action-setup/issues/40)
- Have to upgrade pnpm to version 8 and then fix lock files, for now the installation installs pnpm v7
---

Update CI to use pnpm v7

---

package.json
pnpm-lock.yaml

Description:
- Updated version to 0.3.0
- Updated playwright version to the latest
- Removed conventional-changelog as it uses old tempfile which uses deprecated uuid
@ydcjeff can we replace `conventional-changelog` with something newer ?

Updated deps and versions

---

src/templates/template-text-classification/main.py
src/templates/template-vision-segmentation/main.py

- PyTorch 2.0.0 has deprecated _LRScheduler, use LRScheduler instead
- Imported _LRScheduler or LRScheduler as PyTorchLRScheduler
Fix #232 
---

Fix LRScheduler issue of PyTorch

---

src/templates/template-common/config.yaml
src/templates/template-common/utils.py

- train_epoch_length and eval_epoch_length have been set as optional according to engine definition
Fix #233 
---

Added optional attributes

---

src/templates/template-common/utils.py
src/templates/template-text-classification/main.py
src/templates/template-vision-classification/main.py
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-segmentation/main.py

Updated the output `config-lock.yaml` to be the same as the user config file
---

Updated output config file to be same as config file

---

CONTRIBUTING.md
pyproject.toml
scripts/run_code_style.sh
src/templates/template-common/utils.py
src/templates/template-text-classification/data.py
src/templates/template-text-classification/main.py
src/templates/template-text-classification/trainers.py
src/templates/template-text-classification/utils.py
src/templates/template-vision-classification/main.py
src/templates/template-vision-classification/test_all.py
src/templates/template-vision-classification/utils.py
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-dcgan/test_all.py
src/templates/template-vision-dcgan/trainers.py
src/templates/template-vision-dcgan/utils.py
src/templates/template-vision-segmentation/data.py
src/templates/template-vision-segmentation/main.py
src/templates/template-vision-segmentation/test_all.py
src/templates/template-vision-segmentation/utils.py
src/templates/template-vision-segmentation/vis.py

- Added pyproject.toml to set max line size to 120
- Reformatted with black to 120
- Made black running on dist-tests with pnpm dist_lint

Added pyproject.toml and more code formatting and checks

---

functions/colab.js
src/templates/template-vision-segmentation/README.md

Fix #281 
Added Manual dataset download in colab, modified colab.js 
- Created a new array for commands in colab, this can be used to modify commands for individual templates using `splice`
```js
let commands = [
`!wget ${zipRes}\n`,
`!unzip ${template}.zip\n`,
'!pip install -r requirements.txt\n',
'!python main.py config.yaml\n'
]
```
And then using
```js
source: commands
```
In `const nb`

Added Manual dataset download

---

functions/colab.js
src/components/NavColab.vue

Fix for "open in colab" opens the same zip after updates

---

scripts/requirements.txt
src/templates/template-common/config.yaml
src/templates/template-common/requirements.txt
src/templates/template-common/test_all.py
src/templates/template-common/utils.py
src/templates/template-text-classification/main.py
src/templates/template-text-classification/test_all.py
src/templates/template-vision-classification/main.py
src/templates/template-vision-classification/test_all.py
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-dcgan/test_all.py
src/templates/template-vision-segmentation/main.py
src/templates/template-vision-segmentation/test_all.py

This PR is to introduce [OmegaConf](https://omegaconf.readthedocs.io) as the default config dict for handling hyper parameters in templates. This will be great for the subsequent introduction of python-fire and hydra.
Also we try to have a new `save_config` method as the old method uses `shutil.py`and is quite limited in its scope to save an overridden config using command line. At last, we introduce a test function `test_save_config` to test saved by `save_config` method.
Additionally I plan to remove PyYaml file methods with OmegaConf methods as they work better with Python objects like PosixPath.
---

Change default Namespace to Omegaconf and new method to save config-lock.yaml for reproducibility

---

functions/code.js
functions/colab.js
functions/utils.js
src/components/NavCode.vue
src/components/NavColab.vue

Fix # 
Refactoring some of the code
---

Refactor the code for the netlify functions

---

.github/workflows/ci.yml
__tests__/text-classification.spec.js
__tests__/vision-classification.spec.js
__tests__/vision-dcgan.spec.js
__tests__/vision-segmentation.spec.js
package.json
scripts/run_code_style.sh
scripts/run_tests.sh
src/components/TabTraining.vue
src/metadata/metadata.json
src/store.js
src/templates/template-common/utils.py

This PR introduces Argument Parser UI in the Code-Generator app that lets the user choose which python argument parser they want to use for the templates. This will be followed by introduction of python-fire and hydra in the Code-Generator app.
Also in this PR, we introduce CI changes that can help reduce CI time and test the integration of python-fire and Hydra in subsequent PRs.
Fix # 
---

Updated UI for ArgParser options in TrainingTab.vue

---

src/templates/template-common/utils.py

Changed logger's format in the `training-info.log` from
```
[32m[ignite][0m: Configuration: 
{'seed': 777, 'data_path': './', 'train_batch_size': 512, 'eval_batch_size': 1024, 'num_workers': 4, 'max_epochs': 20, 'use_amp': False, 'debug': False, 'train_epoch_length': None, 'eval_epoch_length': None, 'filename_prefix': 'training', 'n_saved': 2, 'save_every_iters': 1000, 'patience': 3, 'output_dir': PosixPath('logs/20230826-220744-backend-None-lr-0.0001'), 'log_every_iters': 10, 'lr': 0.0001, 'model': 'resnet18', 'backend': None, 'num_iters_per_epoch': None}
[32m[ignite][0m: Engine run starting with max_epochs=20.
[32m[ignite][0m: Engine run starting with max_epochs=1.
[32m[ignite][0m: Epoch[1] Complete. Time taken: 00:00:04.522
[32m[ignite][0m: Engine run complete. Time taken: …
```

Updated logger format

---

src/templates/template-common/test_all.py
src/templates/template-common/utils.py
src/templates/template-text-classification/main.py
src/templates/template-text-classification/test_all.py
src/templates/template-vision-classification/main.py
src/templates/template-vision-classification/test_all.py
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-dcgan/test_all.py
src/templates/template-vision-segmentation/main.py
src/templates/template-vision-segmentation/test_all.py

This PR aims to fix the problems related to reproducing results in the templates due to templates creating output in wrong directory when we try to reproduce the results using `logs/<job-dir>/config-lock.yaml`
Fix #292
This PR uses discussion based on  #306.
---

Fix the output_dir logic and bugs for reproducibility

---

functions/utils.js

- This PR aims to measure the time overhead caused by the current hashing of `store.config` and hashing of the whole code in the template.
Currently, uuid hashes only the current store.config, so any changes in store.config would change the uuid, but suppose we follow the steps:
1. Commit a template using x config with uuid: 53asdf
2. We then change the code in the python files, in the template, this would be reflected in the ui and won't affect the download zip option, but essentially there is no change in the store.config
3. We again try to commit a template using the same x config, so the uuid would be the same: 53asdf since the store.config is the same. This would not create a new commit like it should since we changed the py files, but fetches the template from the previous commit... …

PR to improve the hash function for uuid

---

functions/nebari.js
functions/utils.js

This PR is a follow up PR for the fixes in the code execution while testing in the Nebari server. Particularly we faced two issues, first if we open a template in Nebari, its default folder will be root and if it is the second template opened, then it will try to download and overwrite the previous one. This can be fixed by fixing the `nbuid-> nbuid + '-nebari'`. 
Also we add some extra commands that can help in creating a new directory and store templates files in that specific directory.
Fix #314
This issue was discussed in Discord this week.

Fix command errors in Nebari server run for templates

---

CHANGELOG.md
package.json

This PR provides the `changelog.md` and other changes for release v0.4.0 
---

Updates for v0.4.0 release

---

src/templates/template-text-classification/config.yaml

Update config for text-classification for issue #293

Update config for text-classification
