templates/text_classification/_sidebar.py

Add test options in text classification
---

fix: add test options in text classification

---

app/streamlit_app.py

fix: add `/` in release badge [skip ci]

---

app/streamlit_app.py

fix: add `/` in release badge [skip ci] (#100)

---

.github/workflows/ci.yml
package.json

ci: change lint job 

---

.gitignore
src/components/FormSelect.vue
src/components/Instruction.vue
src/components/PaneLeft.vue
src/components/PaneRight.vue
src/components/PaneSplit.vue

tested on Chrome, Firefox Dev Edition, Firefox, and Safari
Add more CSS to make UI consistent across browsers
---

fix: make UI consistent across browsers

---

src/components/CodeBlock.vue
src/components/Message.vue
src/components/NavBar.vue
src/components/PaneLeft.vue
src/store.js

Part of #103
- Show error if template has not been chosen when click download
- Show error if there is no value for required configs when click download
- Show info after copying code to clipboard.
---

feat: add error and info message box

---

src/components/CodeBlock.vue
src/components/Instruction.vue
src/components/Message.vue
src/components/NavBar.vue
src/store.js

…uction for mobile
- fix bgColor in message box
- use `location.origin` in local dev mode
- change instruction text for mobile
- use margin instead of padding in codeblock
---

fix: no alpha in message box bg, origin url in dev mode, change instruction for mobile

---

src/components/FormCheckbox.vue
src/components/FormInput.vue
src/components/FormRadio.vue
src/components/TabLoggers.vue
src/components/TabTraining.vue
src/metadata/metadata.json
src/templates/template-common/README.md
src/templates/template-common/config.yaml
src/templates/template-vision-classification/README.md
src/templates/template-vision-classification/config.yaml
src/templates/template-vision-dcgan/README.md
src/templates/template-vision-dcgan/config.yaml

This PR makes the app
- have default value in `output_dir` and `log_every_iters`
- distributed training checkbox
- distributed default values (`nproc_per_node`, `nnodes`, `master_addr`, and `master_port`)
- updated READMEs
- updated config.yaml
---

fix: revert back to previous app UX

---

src/components/CodeBlock.vue
src/templates/template-common/README.md
src/templates/template-common/config.yaml
src/templates/template-common/main.py
src/templates/template-common/requirements.txt
src/templates/template-common/utils.py
src/templates/template-vision-classification/README.md
src/templates/template-vision-classification/config.yaml
src/templates/template-vision-classification/main.py
src/templates/template-vision-classification/requirements.txt
src/templates/template-vision-classification/utils.py
src/templates/template-vision-dcgan/README.md
src/templates/template-vision-dcgan/config.yaml
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-dcgan/requirements.txt
src/templates/template-vision-dcgan/utils.py

This PR
- remove hydra configuration library
- remove `backend` from config.yaml
- add back `setup_parser` function
- explicitly set command line options for `--backend`
- `verbose` change to `debug`
- updated commands in READMEs
- updated requirements.txt
---

refactor: remove hydra and use simple pyyaml + argparse

---

.github/workflows/release.yml
CHANGELOG.md
package.json
pnpm-lock.yaml
scripts/release.js

- Add a release script and release github actions
- Add the changelog from v0.1.0 in `CHAGNELOG.md`
To do a release, run:
```sh
pnpm run release
```
The script will do the following:
- It will prompt the versions to choose according to [semver](https://semver.org).
- It will update the version in `package.json`.
- It will generate the changelog into `CHANGELOG.md`
- It will run code formatting
- It will run git commit with message `release: <version tag>`
- It will run git tag and push to GitHub.
---

chore: add a release script and release github actions

---

src/templates/template-vision-segmentation/README.md
src/templates/template-vision-segmentation/config.yaml
src/templates/template-vision-segmentation/data.py
src/templates/template-vision-segmentation/main.py
src/templates/template-vision-segmentation/requirements.txt
src/templates/template-vision-segmentation/trainers.py
src/templates/template-vision-segmentation/utils.py
src/templates/template-vision-segmentation/vis.py
src/templates/templates.json

Add a image segmentation template from ignite example
---

feat(templates): add a image segmentation template

---

src/templates/template-vision-classification/main.py
src/templates/template-vision-dcgan/main.py

Called `set_epoch` of DistributedSampler every start of epoch
---

fix(sampler): call set_epoch every epoch start in distributed training

---

__tests__/vision-classification.spec.js
__tests__/vision-dcgan.spec.js
__tests__/vision-segmentation.spec.js

This PR generates with test zip files with full template names to avoid multiple zip file names overlapped in #131 
---

test: generate zip with full template names

---

src/components/PaneRight.vue

Fix # 
Fixes padding on the right for the tab panel.
---

fix: padding-right for right-pane-tabs 

---

__tests__/text-classification.spec.js
__tests__/vision-classification.spec.js
__tests__/vision-dcgan.spec.js
__tests__/vision-segmentation.spec.js
src/components/TabHandlers.vue
src/metadata/metadata.json
src/store.js
src/templates/template-common/main.py
src/templates/template-common/utils.py
src/templates/template-text-classification/main.py
src/templates/template-text-classification/trainers.py
src/templates/template-text-classification/utils.py
src/templates/template-vision-classification/main.py
src/templates/template-vision-classification/trainers.py
src/templates/template-vision-classification/utils.py
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-dcgan/test_all.py
src/templates/template-vision-dcgan/trainers.py
src/templates/template-vision-dcgan/utils.py
src/templates/template-vision-segmentation/main.py
src/templates/template-vision-segmentation/model.py
src/templates/template-vision-segmentation/trainers.py
src/templates/template-vision-segmentation/utils.py
src/templates/templates.json

fix: address comments from #136

---

src/components/PaneRight.vue

Made margin 0 which is left to do in #139 
---

fix: margin 0 on mobile

---

.github/workflows/ci.yml
src/templates/template-common/main.py
src/templates/template-common/utils.py
src/templates/template-text-classification/main.py
src/templates/template-text-classification/utils.py
src/templates/template-vision-classification/main.py
src/templates/template-vision-classification/utils.py
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-dcgan/utils.py
src/templates/template-vision-segmentation/main.py
src/templates/template-vision-segmentation/utils.py

Upgrade ignite to nightly to test new handlers that are moved from contrib to core module.
---

chore: upgrade ignite to nightly

---

src/templates/template-vision-classification/utils.py
src/templates/template-vision-dcgan/trainers.py
src/templates/template-vision-dcgan/utils.py

Add `score_function` in saving best models in dcgan and classification templates
---

fix: add `score_function` in saving best models

---

src/templates/template-vision-segmentation/data.py
src/templates/template-vision-segmentation/main.py

fix https://github.com/pytorch-ignite/code-generator/issues/103#issuecomment-851067565
- Do not download VOCSegmentation dataset by default
- Add a suggestion for downloading datasets
---

fix: do not download VOCSegmentation by default

---

src/App.vue
src/components/Message.vue
src/components/PaneSplit.vue

fix: sidebar open from right for right pane on mobile
---

fix: sidebar open from right for right pane on mobile

---

src/components/PaneSplit.vue

fix: split the panes by 40/60
ref #103 
---

fix: split the panes by 40/60

---

src/components/FormSelect.vue
src/metadata/metadata.json

Fix the correct naming for loggers
ref #103 
---

fix: correct naming for loggers

---

src/templates/template-common/requirements.txt
src/templates/template-text-classification/requirements.txt
src/templates/template-vision-classification/requirements.txt
src/templates/template-vision-dcgan/requirements.txt
src/templates/template-vision-segmentation/requirements.txt

fix: include pytest in requirements.txt
ref #103
---

fix: include pytest in requirements.txt

---

src/components/FormCheckbox.vue
src/components/PaneLeft.vue
src/components/PaneRight.vue

Disable clicking and show `not-allowed` cursor if there is no chosen template
---

fix: disable clicking if no template is chosen

---

src/main.js

fix: scroll to top when navigate
ref #103 
---

fix: scroll to top after navigation

---

scripts/requirements.txt
src/components/FormCheckbox.vue
src/components/FormInput.vue
src/components/FormRadio.vue
src/components/FormSelect.vue
src/components/TabHandlers.vue
src/components/TabLoggers.vue
src/metadata/metadata.json

- Choose sensible default values for Ignite handlers
- Fix logger value not showing up when choosing
ref #103 
---

fix: make sensible default for handlers

---

src/store.js
src/views/Create.vue

Reset state when switching routes
---

feat: reset state when switching routes

---

.github/workflows/ci.yml
__tests__/text-classification.spec.js
__tests__/vision-classification.spec.js
__tests__/vision-dcgan.spec.js
__tests__/vision-segmentation.spec.js
src/components/NavBar.vue
src/components/NavColab.vue
src/components/NavDownload.vue
src/components/NavHelp.vue
src/components/PaneLeft.vue
src/components/TabTemplates.vue
src/metadata/metadata.json
src/store.js
src/views/Create.vue

ref: https://github.com/pytorch-ignite/code-generator/issues/103#issuecomment-859069323
---

fix: download after template, move download & colab under each left tab

---

src/templates/template-common/main.py
src/templates/template-common/requirements.txt
src/templates/template-text-classification/main.py
src/templates/template-text-classification/requirements.txt
src/templates/template-vision-classification/main.py
src/templates/template-vision-classification/requirements.txt
src/templates/template-vision-dcgan/main.py
src/templates/template-vision-dcgan/requirements.txt
src/templates/template-vision-segmentation/main.py
src/templates/template-vision-segmentation/requirements.txt

Bump pytorch-ignite to v0.4.5
---

chore(deps): bump pytorch-ignite to 0.4.5

---

app/streamlit_app.py

Update link to v0.2.0 app

---

index.html

chore: add google analytics

---

CONTRIBUTING.md
scripts/run_code_style.sh

- Updated black version
- Fixed CONTRIBUTING.md

Updated black version

---

src/templates/template-text-classification/data.py
src/templates/template-vision-dcgan/data.py
src/templates/template-vision-segmentation/data.py

Fix #168 
Remove idist.barrier() if no distribution configuration is specified.

Added configuration for local rank for all the templates

---

scripts/run_tests.sh
src/templates/template-common/README.md
src/templates/template-text-classification/README.md
src/templates/template-vision-classification/README.md
src/templates/template-vision-dcgan/README.md
src/templates/template-vision-segmentation/README.md

Fix #199 
Let me know if I have made some mistake, will correct it out.

Replaced torch.distributed.launch with torchrun

---

.github/workflows/ci.yml

Add GHA CI autocancel

---

.github/workflows/ci.yml
pnpm-lock.yaml

Updates Lock file and installs latest version of pnpm
---

Update lock file

---

functions/colab.js
src/store.js

Description:
- Fixed open in colab
- Change logging frequency

Fix open in colab

---

src/templates/template-vision-classification/data.py
src/templates/template-vision-classification/main.py

Added LR Scheduler for Vision classification

Improve vision classification

---

src/templates/template-common/config.yaml
src/tests/ci-configs/text-classification-all.yaml
src/tests/ci-configs/text-classification-launch.yaml
src/tests/ci-configs/text-classification-simple.yaml
src/tests/ci-configs/text-classification-spawn.yaml
src/tests/ci-configs/vision-classification-all.yaml
src/tests/ci-configs/vision-classification-launch.yaml
src/tests/ci-configs/vision-classification-simple.yaml
src/tests/ci-configs/vision-classification-spawn.yaml
src/tests/ci-configs/vision-dcgan-all.yaml
src/tests/ci-configs/vision-dcgan-launch.yaml
src/tests/ci-configs/vision-dcgan-simple.yaml
src/tests/ci-configs/vision-dcgan-spawn.yaml
src/tests/ci-configs/vision-segmentation-all.yaml
src/tests/ci-configs/vision-segmentation-launch.yaml
src/tests/ci-configs/vision-segmentation-simple.yaml
src/tests/ci-configs/vision-segmentation-spawn.yaml

replace seed 666 -> 777

---

src/templates/template-text-classification/requirements.txt
src/templates/template-vision-classification/requirements.txt
src/templates/template-vision-dcgan/requirements.txt
src/templates/template-vision-segmentation/requirements.txt

This PR is a continuation of PR #260 and fix presence of a common requirements.txt to be followed by all templates.
Fix #260 
---

Add common template for requirements.txt in all templates

---

.github/workflows/ci.yml
src/tests/ci-configs/vision-classification-launch.yaml
src/tests/ci-configs/vision-segmentation-launch.yaml

- Try to enable "launch" for vision-classification/segmentation

Try to enable "launch" for vision-classification/segmentation

---

functions/utils.js

Fix for the Bug which gives the wget link undefined when Opened in Colab
Fix # 
---

Fix bug "Open in Colab" returning "undefined"

---

src/components/NavBar.vue
src/components/NavContributors.vue

- Added "Contributors" button and widget with acknowledgements
@ydcjeff @trsvchn @theory-in-progress @guptaaryan16 please check this PR here : https://deploy-preview-311--code-generator.netlify.app/create. If you do not have any objections that your name is appeared in the list, I'll merge it.
Thanks to you all for your contributions and hope to see more of them!

Added "Contributors" widget and button

---

src/templates/template-common/utils.py

To fix extra lines in Argparse `setup config function` and make it look more clean.
As discussed in discord 
---

Remove extra lines in setup_config for Argparser

---

src/templates/template-vision-classification/config.yaml
src/templates/template-vision-dcgan/config.yaml
src/templates/template-vision-segmentation/config.yaml

Annotation for template-vision-classification,dcgan and segmentation regarding issue #293

Annotation for template-vision-*

---

src/templates/template-common/README.md

Fix: Add backend in common readme for Hydra option in torch.spawn 

---

package.json
src/components/NavToggleDarkMode.vue

Fix #351
Added an if-else statement that checks the theme of the website and sets the button state according to that theme.
-  Bug fix

fixed bug that caused state revert in darkmode button
